name: Pharo CI

on:
  push: 

jobs:
  build-and-test:
    runs-on: ubuntu-latest # you can specify other OS if required

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Pharo
      run: |
        # Commands to setup Pharo on the runner
        wget -O - get.pharo.org/64/90+vmT | bash

    - name: Load code and create image
      run: |
        ./pharo Pharo.image eval --save "
          | loader |
          loader := Metacello new.
          loader
            baseline: 'YourProject';
            repository: 'filetree://$(pwd)/src'.
          loader load.
        "
        ./pharo Pharo.image save MyNewImage

    # Add additional steps to run tests or any other tasks
    - name: Run tests
      run: |
        ./pharo MyNewImage.image test --junit-xml-output 'YourTestPackage.YourTestClass'
