
name: Test

on: [push,pull_request]


jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup smalltalkCI
        uses: hpi-swa/setup-smalltalkCI@1.3.4
        with:
          smalltalk-image: 'Pharo32-stable'
      - name: versions
        run: |
          smalltalkci --version
          pharo --version
      - run: smalltalkci -s Pharo32-stable
        shell: bash       
