name: Pharo CI

on:
  push: 

jobs:
  build-and-test:
    runs-on: macos-latest # you can specify other OS if required

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Pharo
      uses: hpi-swa/setup-smalltalkCI@1.3.4
      with:
        smalltalk-image: Pharo32-stable

    - name: Load code and create image
      run: |
        smalltalkci -s 
