name: Pharo CI

on:
  workflow_dispatch:
  # push: 

jobs:
  build-and-test:
    runs-on: macos-latest # you can specify other OS if required

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Pharo
      uses: hpi-swa/setup-smalltalkCI@1.3.4
      with:
        smalltalk-image: Pharo64-11

    - name: Load code and create image
      run: |
        smalltalkci -s 'smalltalkci -s Pharo64-11'
        shell: bash
        timeout-minutes: 15
